# Generated by Django 5.2.16 on 2026-07-18 13:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='queues', to='canary.site'),
        ),
        migrations.CreateModel(
            name='PassiveSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('njobs', models.PositiveIntegerField(default=0)),
                ('wait_median_s', models.FloatField(blank=True, null=True)),
                ('wait_p90_s', models.FloatField(blank=True, null=True)),
                ('failure_rate', models.FloatField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passive_samples', to='canary.queue')),
            ],
            options={
                'db_table': 'canary_passive_sample',
                'ordering': ['-window_end'],
                'indexes': [models.Index(fields=['queue', '-window_end'], name='canary_sample_queue_time_idx')],
            },
        ),
    ]
