# Generated by Django 5.2.12 on 2026-09-01 17:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canary', '0004_queue_status_v1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbeRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jeditaskid', models.BigIntegerField(blank=True, null=True)),
                ('trigger', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='auto', max_length=16)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('failed_submit', 'Failed Submit'), ('finished', 'Finished'), ('failed', 'Failed'), ('collected', 'Collected')], default='submitted', max_length=16)),
                ('submitted_at', models.DateTimeField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='probe_runs', to='canary.queue')),
            ],
            options={
                'db_table': 'canary_probe_run',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['queue', '-submitted_at'], name='canary_probe_queue_time_idx')],
            },
        ),
    ]
