# Generated by Django 5.2.12 on 2026-09-07 20:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canary', '0006_seed_osg_probe_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('processor', models.CharField(default='unknown', max_length=200)),
                ('container_image', models.CharField(blank=True, default='', max_length=300)),
                ('detector_version', models.CharField(blank=True, default='', max_length=50)),
                ('physics_config', models.CharField(blank=True, default='', max_length=32)),
                ('payload_version', models.CharField(blank=True, default='', max_length=32)),
                ('stage', models.CharField(max_length=64)),
                ('metrics', models.JSONField(default=dict)),
                ('jobs', models.PositiveIntegerField(default=0)),
                ('first_job_at', models.DateTimeField(blank=True, null=True)),
                ('last_job_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('node_environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to='canary.nodeenvironment')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='canary.queue')),
            ],
            options={
                'db_table': 'canary_node_measurement',
                'ordering': ['queue', 'processor', 'stage'],
                'indexes': [models.Index(fields=['queue', 'processor'], name='canary_measure_queue_proc_idx')],
                'constraints': [models.UniqueConstraint(fields=('queue', 'processor', 'container_image', 'detector_version', 'physics_config', 'payload_version', 'stage'), name='canary_measure_key_uniq')],
            },
        ),
    ]
