# Generated by Django 5.2.12 on 2026-09-14 21:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canary', '0007_node_measurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=200)),
                ('site', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('clear', 'Clear'), ('black_hole', 'Black hole'), ('half_open', 'Half open'), ('pinned', 'Pinned')], default='clear', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=64)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('last_verdict', models.JSONField(blank=True, default=dict)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reopened', models.PositiveIntegerField(default=0)),
                ('trips', models.PositiveIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('node_environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_states', to='canary.nodeenvironment')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='node_states', to='canary.queue')),
            ],
            options={
                'db_table': 'canary_node_state',
                'ordering': ['queue', 'host'],
            },
        ),
        migrations.CreateModel(
            name='NodeStateChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=16)),
                ('new_status', models.CharField(max_length=16)),
                ('actor', models.CharField(choices=[('guard', 'Guard'), ('manual', 'Manual')], max_length=16)),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('reason', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='canary.nodestate')),
            ],
            options={
                'db_table': 'canary_node_state_change',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='nodestate',
            index=models.Index(fields=['status', '-modified_at'], name='canary_node_state_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='nodestate',
            constraint=models.UniqueConstraint(fields=('queue', 'host'), name='canary_node_state_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='nodestatechange',
            index=models.Index(fields=['node', '-created_at'], name='canary_node_change_time_idx'),
        ),
    ]
